version: '3.7'

services:

  web:
    container_name: front-korrigans
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    env_file:
      - .env
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true