version: '3.7'

services:

  web:
    container_name: front-korrigans
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=korrigans-team2.lpweb-lannion.fr
      - VIRTUAL_PORT=3001
      - LETSENCRYPT_HOST=korrigans-team2.lpweb-lannion.fr
      - LETSENCRYPT_EMAIL=team2korrigans@gmail.com