version: '3.7'

services:

  web:
    container_name: front-korrigans
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=korrigans-team2.lpweb-lannion.fr
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=korrigans-team2.lpweb-lannion.fr
      - LETSENCRYPT_EMAIL=team2korrigans@gmail.com
    networks:
      - webproxy_back

networks:
  webproxy_back:
    external: true