version: '3.7'

services:

  web:
    container_name: front-korrigans
    build:
      context: .
      dockerfile: Dockerfile-front
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:80
    environment:
      - CHOKIDAR_USEPOLLING=true