version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-back
    restart: unless-stopped
    ports:
      - ${API_PORT}:80
    environment:
      #  - VIRTUAL_HOST=korrigans-ws.fabulapps.com
      #  - LETSENCRYPT_HOST=korrigans-ws.fabulapps.com
      #  - LETSENCRYPT_EMAIL=gildas@bigpapoo.com
       - docker="true"
    networks:
      - back
      # - webproxy_back
    volumes:
      - ./data/www:/var/www/
      - ./files/php-tweak.ini:/usr/local/etc/php/conf.d/php-tweak.ini

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d/
    networks:
      - back

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=mysql
      # - VIRTUAL_HOST=korrigans-db.fabulapps.com
      # - LETSENCRYPT_HOST=korrigans-db.fabulapps.com
      # - LETSENCRYPT_EMAIL=gildas@bigpapoo.com
    networks:
      - back
      # - webproxy_back

networks:
  back:
  # webproxy_back:
  #   external: true
